package org.companerodeescuela.api.plugins

import io.ktor.http.HttpHeaders
import io.ktor.http.HttpMethod
import io.ktor.http.HttpStatusCode
import io.ktor.serialization.kotlinx.json.json
import io.ktor.server.application.Application
import io.ktor.server.application.ApplicationCall
import io.ktor.server.application.install
import io.ktor.server.application.log
import io.ktor.server.auth.Authentication
import io.ktor.server.auth.jwt.JWTPrincipal
import io.ktor.server.auth.jwt.jwt
import io.ktor.server.plugins.callid.CallId
import io.ktor.server.plugins.callid.callId
import io.ktor.server.plugins.calllogging.CallLogging
import io.ktor.server.plugins.contentnegotiation.ContentNegotiation
import io.ktor.server.plugins.cors.routing.CORS
import io.ktor.server.plugins.defaultheaders.DefaultHeaders
import io.ktor.server.plugins.statuspages.StatusPages
import io.ktor.server.request.httpMethod
import io.ktor.server.request.path
import io.ktor.server.response.respond
import io.ktor.server.response.header
import kotlinx.serialization.json.Json
import org.companerodeescuela.api.auth.AuthTokenService
import org.companerodeescuela.api.auth.RefreshSessionRepository
import org.companerodeescuela.api.auth.PlatformSessionAuthority
import org.companerodeescuela.api.config.ApiSettings
import org.companerodeescuela.api.errors.ApiException
import org.companerodeescuela.api.errors.toApiError
import org.companerodeescuela.shared.contracts.AccountStatus
import org.companerodeescuela.shared.contracts.ApiError
import org.companerodeescuela.shared.contracts.ApiErrorCode
import org.slf4j.event.Level
import io.ktor.util.AttributeKey
import kotlinx.coroutines.CancellationException

/**
 * JSON format used by every endpoint.
 *
 * `ignoreUnknownKeys` keeps older Android builds working when a new optional
 * field is added, which is what makes the contract forward compatible.
 */
val ApiJson: Json = Json {
    prettyPrint = false
    isLenient = false
    ignoreUnknownKeys = true
    explicitNulls = false
    encodeDefaults = true
}

/** Header used to correlate a client report with server logs. */
const val REQUEST_ID_HEADER: String = "X-Request-Id"

private val QUIET_PATHS = setOf("/health", "/ready", "/version")

private const val NO_REQUEST_ID = "no-request-id"
private val AUTHORITY_UNAVAILABLE = AttributeKey<Boolean>("liveIdentityAuthorityUnavailable")

/**
 * Request correlation id, generated by the `CallId` plugin.
 *
 * Echoed in the `X-Request-Id` response header and in every error payload so a
 * user-reported failure can be traced to exact log lines.
 */
fun ApplicationCall.requestId(): String? = callId

/**
 * Installs cross-cutting plugins.
 *
 * Install order matters:
 * 1. `DefaultHeaders` first, so every later response already has the baseline.
 * 2. `CallId` before `CallLogging`, so every log line carries the request id.
 * 3. `StatusPages` before routes, so route exceptions can be translated.
 */
fun Application.configurePlugins(
    settings: ApiSettings,
    refreshSessions: RefreshSessionRepository? = null,
    sessionAuthority: PlatformSessionAuthority? = null,
) {
    if (settings.hasAuthentication) {
        requireNotNull(refreshSessions) { "Authentication requires a session repository" }
        requireNotNull(sessionAuthority) { "Authentication requires live identity authority" }
    }
    install(DefaultHeaders)

    install(CallId) {
        header(REQUEST_ID_HEADER)
        generate { java.util.UUID.randomUUID().toString() }
        verify { it.isNotBlank() }
    }

    install(CallLogging) {
        level = Level.INFO
        mdc("requestId") { call -> call.requestId() ?: NO_REQUEST_ID }
        // Liveness probes are frequent and carry almost no diagnostic value.
        filter { call -> call.request.path() !in QUIET_PATHS }
        format { call ->
            val status = call.response.status()?.value ?: 0
            "${call.request.httpMethod.value} ${call.request.path()} -> $status"
        }
    }

    install(ContentNegotiation) {
        json(ApiJson)
    }

    install(CORS) {
        allowMethod(HttpMethod.Get)
        allowMethod(HttpMethod.Post)
        allowMethod(HttpMethod.Put)
        allowMethod(HttpMethod.Patch)
        allowMethod(HttpMethod.Delete)
        allowHeader(HttpHeaders.ContentType)
        allowHeader(HttpHeaders.Authorization)
        allowHeader(REQUEST_ID_HEADER)
        if (!settings.environment.isProduction) {
            allowHost("localhost", schemes = listOf("http"))
            allowHost("127.0.0.1", schemes = listOf("http"))
        }
    }

    install(Authentication) {
        settings.jwtSecret?.let {
            val tokenService = AuthTokenService(settings)
            jwt(AuthTokenService.PROVIDER_NAME) {
                realm = AuthTokenService.REALM
                verifier(tokenService.verifier)
                validate { credential ->
                    try {
                        val sessionId = tokenService.sessionIdFrom(credential.payload)
                        val session = sessionId?.let { refreshSessions?.find(it) }
                        if (session != null && sessionAuthority?.permits(credential.payload, session, tokenService) == true &&
                            (tokenService.userFrom(credential.payload).accountStatus == AccountStatus.ACTIVE ||
                                request.path() in setOf("/auth/me", "/auth/verification/resend", "/auth/verification/confirm"))) {
                            val user = tokenService.userFrom(credential.payload)
                            // A basic workshop account has no academic access, even on coarse authenticated routes.
                            if (user.roles == setOf(org.companerodeescuela.shared.contracts.UserRole.WORKSHOP_PARTICIPANT) &&
                                !request.path().startsWith("/auth/") && request.path() != "/workshops" &&
                                !request.path().startsWith("/workshops/")) null
                            else JWTPrincipal(credential.payload)
                        } else null
                    } catch (cancelled: CancellationException) {
                        throw cancelled
                    } catch (_: Exception) {
                        // Ktor otherwise treats storage/provider exceptions as an authentication rejection.
                        // Preserve transient failure without logging credentials, identifiers or vendor payloads.
                        attributes.put(AUTHORITY_UNAVAILABLE, true)
                        null
                    }
                }
                challenge { scheme, challengeRealm ->
                    val unavailable = call.attributes.getOrNull(AUTHORITY_UNAVAILABLE) == true
                    if (!unavailable) call.response.header(HttpHeaders.WWWAuthenticate, "$scheme realm=\"$challengeRealm\"")
                    call.respond(
                        if (unavailable) HttpStatusCode.ServiceUnavailable else HttpStatusCode.Unauthorized,
                        ApiError(
                            code = if (unavailable) ApiErrorCode.DEPENDENCY_UNAVAILABLE else ApiErrorCode.UNAUTHORIZED,
                            message = if (unavailable) "Identity authority is temporarily unavailable" else "Authentication is required",
                            requestId = call.requestId(),
                        ),
                    )
                }
            }
        }
    }

    val appLogger = log
    install(StatusPages) {
        exception<ApiException> { call, cause ->
            if (cause is ApiException.RateLimited) cause.retryAfterSeconds?.let {
                call.response.headers.append(HttpHeaders.RetryAfter, it.toString())
            }
            call.respond(
                status = cause.httpStatus,
                message = cause.toApiError(call.requestId()),
            )
        }
        exception<Throwable> { call, cause ->
            appLogger.error("Unhandled exception for request ${call.requestId()}", cause)
            call.respond(
                status = HttpStatusCode.InternalServerError,
                message = ApiError(
                    code = ApiErrorCode.INTERNAL_ERROR,
                    message = "Unexpected server error",
                    requestId = call.requestId(),
                ),
            )
        }
        status(HttpStatusCode.NotFound) { call, _ ->
            call.respond(
                status = HttpStatusCode.NotFound,
                message = ApiError(
                    code = ApiErrorCode.NOT_FOUND,
                    message = "Resource not found",
                    requestId = call.requestId(),
                ),
            )
        }
    }
}
